config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
   # resources :agenda, only: [:new, :create, :index, :show]
   resources :classrooms
   resources :classrooms do
    resources :students, only: :index
   end
  #end
  resources :agendas do#, only: [:edit, :update, :destroy]
    resources :students, only: :index do
      collection do
        get :check
      end
    resources :attendances, only: :create
    end
  end
  resources :events
  resources :students, only: [:show, :edit, :update]
  resources :attendances, only: :destroy
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/agenda.rb
class Agenda < ApplicationRecord
  belongs_to :teacher, class_name: "User", foreign_key: "user_id"
  belongs_to :classroom
  has_many :attendances, dependent: :destroy
  validates :start_time, :end_time, presence: true
   after_create :create_attendances

  def create_attendances
    self.classroom.students.each do |student|
      Attendance.create!(agenda: self, student: student)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
 belongs_to :student
 belongs_to :agenda
 validates :is_present?, presence: true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
    has_many :students, dependent: :destroy
    has_many :agendas
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :teacher, class_name: "User", foreign_key: "user_id"
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :parent, class_name: "User", foreign_key: "user_id"
  belongs_to :classroom
  has_many :attendances
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :agendas
  has_many :events
  has_many :children, class_name: "Student", foreign_key: "student_id" #parent view students as children
end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
 def index
   @agendas = Agenda.order(:start_time)
 end

  def show
    @agenda = Agenda.find(params[:id])
  end

 def new
   @agenda = Agenda.new
 end

 def create
    @agenda = Agenda.new(agendas_params)
    @agenda.teacher = current_user
    if @agenda.save
     redirect_to agendas_path
    else
      render :new
    end
 end

  def update
    @agenda = Agenda.find(params[:id])
    @agenda.update(params[:agenda])
    redirect_to agenda_path(@agenda)
  end

 def destroy
    @agenda = Agenda.find(params[:id])
    @agenda.destroy
    redirect_to agendas_path
 end

 private

 def agendas_params
   params.require(:agenda).permit(:start_time, :end_time, :classroom_id)
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
 def default_url_options
   { host: ENV["DOMAIN"] || "localhost:3000" }
 end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def index
   @attendances = Attendance.all.order(created_at: :desc)
  end

  def create
    student = Student.find(params[:student_id])
    agenda = Agenda.find(params[:agenda_id])
    @attendance = Attendance.new
    @attendance.student = student
    @attendance.agenda = agenda
    if @attendance.save
      redirect_to check_agenda_students_path(agenda, anchor: "student-#{student.id}")
    end
  end

  def destroy
    @attendance = Attendance.find(params[:id])
    student = @attendance.student
    if @attendance.destroy
      # redirect_to controller: 'students', action: 'check', agenda_id: @attendance.agenda.id, anchor: "student-#{@attendance.student.id}"
      redirect_to check_agenda_students_path(@attendance.agenda, anchor: "student-#{student.id}"), notice: "Message sent to #{student.parent.name}: 'Your child is missing from school ! 👮' "
    end
  end
 private

  def attendance_params
   # params.require(:attendance).permit(:)
  end

end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
    def index
        @classrooms = Classroom.all
      end
     
       def create
         @classroom = Classroom.new(classroom_params)
         @classroom.teacher = current_user
         @classroom.save
         redirect_to classrooms_path
       end
     
       def new
         @classroom = Classroom.new(params[:classroom])
         @classroom.save
     
       end
     
       def show
        @classroom = Classroom.find(params[:id])
       end
     
       def update
         @classroom = Classroom.find(params[:id])
         @classroom.update(classroom_params)
         redirect_to classroom_path(@classroom)
       end
     
       def edit
         @classroom = Classroom.find(params[:id])
       end
     
       def destroy
         @classroom = Classroom.find(params[:id])
         @classroom.destroy
          redirect_to classrooms_path
       end
     
      private
     
       def classroom_params
          params.require(:classroom).permit(:level)
       end
     end
     

app/controllers/events_controller.rb
class EventsController < ApplicationController
 def index
   @events = Event.all
   if params[:query].present?
    sql_query = "name ILIKE :query"
    @events = Event.where(sql_query, query: "%#{params[:query]}%")
  else
    @events = Event.all.order(created_at: :desc)
  end
 end

  def create
    @event = Event.new(event_params)
    @event.teacher = current_user
    if @event.save
     redirect_to events_path
    else
      render :new
    end
  end

  def new
    @event = Event.new(params[:event])
    @event.save

  end

  def show
   @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to event_path(@event)
  end

  def edit
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
     redirect_to events_path
  end

 private

  def event_params
     params.require(:event).permit(:name, :event_description, :additional_information, :date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @classroom = Classroom.find(params[:classroom_id])
   if params[:query].present?
     sql_query = "name ILIKE :query"
     @students = Student.where(classroom: @classroom).where(sql_query, query: "%#{params[:query]}%")
   else
    @students = Student.where(classroom: @classroom)
   end
  end

  def check
    @agenda = Agenda.find(params[:agenda_id])
    @classroom = @agenda.classroom
    @students = Student.where(classroom: @classroom)
  end

  def create
   @student = Student.new(student_params)
   @student.parent = current_user
    if @student.save
     redirect_to students_path
   else
     render :new
   end
  end

  def show
   @student = Student.find(params[:id])
  end

 def new
    @student = Student.new(params[:student])
    @student.save
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    redirect_to student_path(@student)
  end

  def edit
    @student = Student.find(params[:id])
  end


  def destroy
   @student = Student.find(params[:id])
    @student.destroy
   redirect_to students_path
  end

 private

 def student_params
   params.require(:student).permit(:name, :classroom, :address, :age, :remark)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/agendas/edit.html.erb
<div class="agenda-show">
<%= form_for(@agenda) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :date %>
  <%= f.text_field :date %>
  <%= f.label :start_time %>
  <%= f.number_field :start_time %>
  <%= f.text_field :end_time %>
  <%= f.label :end_time %>
  <%= f.submit %>
<% end %>
<%= link_to 'Back', new_subject_agenda_path(@agenda)%>
</div>

app/views/agendas/index.html.erb
<div class ="school-background">
<div class="cover py-5  mb-40 d-flex align-items-center justify-content-center" >




  <h1 id="lectures_index" style="height: 24px;"></h1>

</div>

<div class= "row justify-content-center ">
  <div class ="col-10">
  <% @agendas.each do |agenda| %>
    <div class="d-flex align-items-center justify-content-center">
     <h3><kbd><%= agenda.start_time.strftime("%A %d %B") %></kbd></h3>
   </div>
   <div class="cover mb-4 d-flex align-items-center justify-content-center" >
         <div class="card-product">
           <div class="card-product-infos">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h2><%= link_to agenda.teacher.subject, agenda_path(agenda) %></h2>
                    <p><strong>From: <%= agenda.start_time.strftime("%H:%M") %> - To: <%= agenda.end_time.strftime("%H:%M") %> </strong></p>
                    <p><strong><%= agenda.classroom.level %></strong></p>
                </div>
                <%= link_to "Attendance", check_agenda_students_path(agenda), class: "btn btn-add mt-0"%>
              </div>
           </div>
         </div>
       </div>
  <% end %>
  </div>
</div>
<div class="cover d-flex align-items-center justify-content-center" >
  <%= link_to "Add", new_agenda_path(@agenda), class: 'text-center', class: 'btn btn-add m-4'%>
</div>
</div>

app/views/agendas/new.html.erb
<div class="school-background">
<div class= "container py-5 mb-40">
  <div class= "d-flex align-items-center justify-content-center mb-4">
   <h2><strong>Create A new Lecture</strong><h2>
  </div>


  <div class= "bg-white rounded shadow h-100 card-body align-items-center py-5 form-new">
    <%= simple_form_for(@agenda) do |f| %>
      <%= f.association :classroom, label_method: :level, as: :select %>
      <div>
       <%= f.input :start_time, as: :datetime, html5: true %>
      </div>
      <br>
      <div>
       <%= f.input :end_time, as: :datetime, html5: true %>
      </div>

      <div class= "d-flex align-items-center justify-content-center mb-4">
       <%= f.submit "Create", class: 'btn btn-gradient' %>
        <%= link_to 'Cancel', :back, class: 'btn btn-ghost' %>
      </div>

    <% end %>
  </div>
</div>
</div>

app/views/agendas/show.html.erb
<div class="school-background">
<div class= "container py-5 mb-40">
  <div class= "d-flex align-items-center justify-content-center mb-4">
   <h2><strong>Agenda</strong><h2>
  </div>

  <div class= "container">
    <div class="d-flex row justify-content-center">
     <div class="col-sm-8">
       <div class="card bg-light my-3">
          <ul class="list-group list-group-flush">
           <li class="list-group-item">
             <p><strong>Classroom <%= @agenda.classroom.level %></strong></p>
             <p><strong>Start_time: <%= @agenda.start_time %></strong></p>
             <p><strong>End_time: <%= @agenda.end_time %></strong></p>
           </li>
          </ul>

          <%= link_to "update", edit_agenda_path(@agenda), class: 'text-center', class: 'btn btn-gradient m-4'%>
          <%= link_to "Delete",agenda_path(@agenda), method: :delete,data: { confirm: "Are you sure?" },class: 'text-center', class: 'btn btn-ghost m-4' %>

        <div class= "d-flex align-items-center justify-content-center mb-4">
          <%= link_to 'Back', agendas_path(@agenda), class: 'text-center', class: 'btn btn-gradient m-4' %>
        </div>

      <div>
    </div>
  </div>
</div>
</div>

app/views/attendances/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center" >
  <h1><strong>Attendance</strong></h1>
</div>

app/views/attendances/show.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center" >
  <h1><strong>Attendance</strong></h1>
</div>

app/views/classrooms/index.html.erb
<div class ="school-background">

<div class="cover py-5 mb-40 d-flex align-items-center justify-content-center" >
 <h1 id="classrooms_index"></h1>
</div>


<br>
<div class="search box">
   <%= form_tag classrooms_path, method: :get do %>
   <div class="search-event mb-4 d-flex" >
    <%= text_field_tag :query,
      params[:query],
      class: "form-control mr-3",
      placeholder: "Find a class..."
    %>

      <%= submit_tag "Search", class: "btn search-btn" %>
      </div>
  <% end %>
</div>


<div class="cover py-4 d-flex align-items-center justify-content-center" >
  <div class= "row justify-content-center w-100">
    <% @classrooms.each do |classroom| %>
      <div class ="col-10">
        <div class="card-product">
          <div class="card-product-infos">
            <%= link_to classroom_students_path(classroom) do %>
              <h2><i class="fas fa-chalkboard"></i>&ensp;&ensp;<%= classroom.level%></h2>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/events/edit.html.erb
<div class="sky-background">
<div class= "container py-5 mb-40">
  <div class= "d-flex align-items-center justify-content-center mb-4">
   <h2><strong>Edit this event</strong><h2>
  </div>


    <div class= "bg-white rounded shadow h-100 card-body align-items-center py-5 form-new">
        <%= form_for(@event) do |f| %>
          <div>
          <%= f.label :name %>
          <%= f.text_field :name %>
          </div>
          <br>
          <div>
          <%= f.label :event_description %>
          <%= f.text_field :event_description%>
          </div>
          <br>
          <div>
           <%= f.label :additional_information %>
           <%= f.text_field :additional_information%>
          </div>
          <br>
          <div>
          <%= simple_form_for ([@event]), remote: true do |f| %>
          <%= f.input :date, as: :date, html5: true, input_html: {class: 'form-input'} %>
         </div>
          <div class= "d-flex align-items-center justify-content-center mb-4">
              <%= f.submit "update", class: 'btn btn-gradient' %>
              <%= link_to 'Cancel', :back, class: 'btn btn-ghost' %>
          </div>
      <% end %>
      <% end %>
    </div>
</div>
</div>

app/views/events/index.html.erb
<div class="sky-background ">


<div class="cover py-4 mb-4 d-flex align-items-center justify-content-center" >
  <h1 id="event_index"></h1>
</div>

<br>
<div class="search box">
   <%= form_tag events_path, method: :get do %>
   <div class="search-event mb-4 d-flex" >
    <%= text_field_tag :query,
      params[:query],
      class: "form-control mr-4",
      placeholder: "Find an event..."
   %>

      <%= submit_tag "Search", class: "btn search-btn" %>
      </div>
  <% end %>
</div>



<div class="container cover mb-4 d-flex align-items-center justify-content-center">
  <div class= "row justify-content-center w-100">
   <div class="col-11">
     <% @events.each do |event| %>
       <div class="card-product">
         <div class="card-product-infos">
           <%= link_to event_path(event) do %>
             <h2><i class="fas fa-calendar-check"></i>&ensp;&ensp;<%= event.name%></h2>
             <p>&ensp;&ensp;<%= event.date.strftime("%A %d %B") %></p>
           <% end %>
         </div>
       </div>
     <% end %>
     <div class="cover mx-auto d-flex align-items-center justify-content-center" >
       <%= link_to "Add", new_event_path(@event), class: 'text-center', class: 'btn btn-add m-4'%>
     </div>
   </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="sky-background">
<div class= "container py-5 mb-40">
  <div class= "d-flex align-items-center justify-content-center mb-4">
   <h2><strong>Create a new event</strong><h2>
  </div>

    <div class= "bg-white rounded shadow h-100 card-body align-items-center py-5 form-new">
        <%= simple_form_for(@event) do |f| %>
         <div>
           <%= f.input :name %>

           <%= f.input :event_description %>

           <%= f.input :additional_information %>
         </div>
         <br>

         <div>
           <%= simple_form_for ([@event]), remote: true do |f| %>
           <%= f.input :date, as: :date, html5: true, input_html: {class: 'form-input'} %>
         </div>


         <div class= "d-flex align-items-center justify-content-center mb-4">
           <%= f.submit "Add event", class: 'btn btn-gradient' %>
           <%= link_to 'Cancel', events_path(@event), class: 'btn btn-ghost' %>
         </div>
        <% end %>
          <% end %>
    </div>
</div>
</div>

app/views/events/show.html.erb
    <div class="sky-background">
      <div class="container">
         <div cover mb-4 d-flex align-items-center justify-content-center >

         </div>
          <div class="d-flex row justify-content-center">
            <div class="col-lg-4">
               <div class="card bg-light my-3">
                    <div class="card-body d-flex align-items-center">
                      <h2 class="card-title fw-bolder"> <%= @event.name %></h2>
                        </div>
                          <ul class="list-group list-group-flush">
                           <li class="list-group-item">
                           <p><strong>Event: </strong><%= @event.name%></p>
                           <p><strong>Event Description: </strong><%= @event.event_description%></p>
                           <p><strong>Additional Information: </strong><%= @event.additional_information%></p>
                           <p><strong>Date: </strong><%= @event.date%></p>


                           </li>

                          </ul>
                                <%= link_to "update", edit_event_path(@event), class: 'text-center', class: 'btn btn-gradient m-4'%>

                                <%= link_to "Delete",event_path(@event),
                                method: :delete,
                                data: { confirm: "Are you sure?" },class: 'text-center', class: 'btn btn-ghost m-4' %>
                </div>
                  <div class= "d-flex align-items-center justify-content-center mb-4">
        <%= link_to 'Back', events_path(@event), class: 'text-center', class: 'btn btn-gradient m-4' %>
           </div>
            </div>
          </div>


      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Hotjar Tracking Code for https://one-cliqk.herokuapp.com/ -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:2741441,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script> 
    <title>OneCliq-Connecting Parents And School Together!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
     <title><%= meta_title %></title>
   <meta name="description" content="<%= meta_description %>">

   <!-- Facebook Open Graph data -->
   <meta property="og:title" content="<%= meta_title %>" />
   <meta property="og:type" content="website" />
   <meta property="og:url" content="<%= request.original_url %>" />
   <meta property="og:image" content="<%= meta_image %>" />
   <meta property="og:description" content="<%= meta_description %>" />
   <meta property="og:site_name" content="<%= meta_title %>" />

   <!-- Twitter Card data -->
   <meta name="twitter:card" content="summary_large_image">
   <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
   <meta name="twitter:title" content="<%= meta_title %>">
   <meta name="twitter:description" content="<%= meta_description %>">
   <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
   <meta name="twitter:image:src" content="<%= meta_image %>">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag %>
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
      <!--<p class="alert"><%= alert %></p>
      <p class="notice"><%= notice %></p>-->
    <%= yield %>
     <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Made with <i class="fas fa-heart"></i> by OneCliQ™
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-logo">


  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png", alt: "logo" %>

  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon">
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to " | Home |", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "| Lectures |", agendas_path, class: "nav-link" %>

        </li>

        <li class="nav-item">
          <%= link_to "| Your classes |", classrooms_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "| Events |", events_path, class: "nav-link" %>

        </li>

        <li class="nav-item dropdown">
          <%= image_tag "sonali.png" , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "View Profile", "#", class: "dropdown-item" %>
            <%= link_to "Reminder", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/students/check.html.erb
<div class="school-background py-4">
<br>
<div class="student mb-4 d-flex align-items-center justify-content-center" >
  <h1 id="attendances_index"></h1>
</div>

<div class="cover mb-4 d-flex align-items-center justify-content-center" >
  <div class= "row justify-content-center w-100">
    <div class ="col-10">
     <% @students.each do |student| %>
     <%= link_to  student_path(student) do %>
       <div id="student-<%= student.id %>" class="card-product">
         <img src= "<%= student.photo %>" />
         <div class="card-product-infos d-flex justify-content-between w-100">
             <div>
             <h2><i class="fas fa-graduation-cap"></i>&ensp;&ensp;<%= student.name %></h2>
             <p>&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;<%= student.classroom.level %></p>
            </div>

            <div class ="wrapper">
                 <% attendance = student.attendances.find{ |attendance| attendance.agenda == @agenda } %>
              <% if attendance %>
                <%= link_to attendance_path(attendance), method: :delete, remote: true do %>
                  <i class="fas fa-check-square attendance-present"></i>
                <% end %>
              <% else %>
                <%= link_to agenda_student_attendances_path(@agenda, student), method: :post, remote: true do %>
                  <i class="fas fa-times-circle attendance-absent"></i>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
         <% end %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/students/index.html.erb
<div class="school-background py-4">

<div class="student d-flex align-items-center justify-content-center" >
 <h1 id="lists_index"></h1>

</div>

<div class="search box">
   <%= form_tag classroom_students_path, method: :get do %>
  <div class="search-event mb-2 d-flex" >
    <%= text_field_tag :query,
      params[:query],
      class: "form-control mr-3",
      placeholder: "Find a Student..."
    %>
    <%= submit_tag "Search", class: "btn search-btn" %>
  </div>
  <% end %>
</div>


<div class="cover mb-4 d-flex align-items-center justify-content-center" >
  <div class= "row justify-content-center">
    <% @students.each do |student| %>
      <div class ="col-10">
        <div class="card-product">
           <img src= "<%= student.photo %>" />
          <div class="card-product-infos">
            <%= link_to student_path(student) do %>

             <h2><i class="fas fa-graduation-cap"></i>&ensp;&ensp;<%= student.name %></h2>
               <p>&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;<%= student.classroom.level %></p>
            <% end %>
           <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/students/show.html.erb
<div class ="school-background">
<div class= "container py-5 mb-40">
  <div class= "d-flex align-items-center justify-content-center mb-4">
   <h2><strong>Student Profile</strong><h2>
  </div>

  <div class= "container">
    <div class="d-flex row justify-content-center">
     <div class="col-sm-8">
       <div class="card bg-light my-3">
         <div class="card-body d-flex align-items-center">
           <h2><strong>Name: <%= @student.name %></strong></h2>
          </div>


           <ul class="list-group list-group-flush">
            <li class=" d-flex list-group-item">
              <img src="<%= @student.photo %>">
              <div class= "ml-5">
               <p><strong>Age: <%= @student.age %></strong></p>
               <p><strong>Classroom: <%= @student.classroom.level %></strong></p>
               <p><strong>Address: <%= @student.address %></strong></p>
               <p><strong>Contact: <%= @student.contact %></strong></p>
               <p><strong>Remarks: <%= @student.remark %></strong></p>
             </div>
            </li>
           </ul>

          <%= link_to "update", edit_student_path(@student), class: 'text-center', class: 'btn btn-gradient m-4'%>
          <%= link_to "Delete",student_path(@student), method: :delete,data: { confirm: "Are you sure?" },class: 'text-center', class: 'btn btn-ghost m-4' %>
        </div>
        <div class= "d-flex align-items-center justify-content-center mb-4">
          <%= link_to 'Back', classroom_students_path(@student.classroom), class: 'text-center', class: 'btn btn-gradient m-4' %>
        </div>
      <div>
    </div>
  </div>
</div>
</div>

 <!--student: name,classroom,  age, address, contact, remarks(results, behaviour)